---
- name: Create aur_builder
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: no
    group: sudo

- name: Add aur_builder to sudoers
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"

- name: Check yay installation
  ansible.builtin.shell: '! [-x "$(command -v yay)"]'
  register: yay_command_result

- block:
    - name: Clone yay PKBUILD
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ ansible_facts['user_dir'] }}/yay"

    - name: Install yay
      become: yes
      become_user: aur_builder
      aur:
        use: makepkg
        local_pkgbuild: "{{ ansible_facts['user_dir'] }}/yay"
  when: yay_command_result.rc == 0

- name: Install AUR packages (yay)
  aur:
    use: yay
    aur_only: yes
    name: "{{ name }}"
    state: "{{ state }}"
