---
collections:
  - name: community.general
  - name: community.sops
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: community.windows
  # https://github.com/kewlfft/ansible-aur
  - name: kewlfft.aur
