---
- name: Sync dotfiles
  hosts: all
  pre_tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          # TODO: move package lists to separate file?
          - git
          - python-virtualenvwrapper
        state: present
      tags: update
  roles:
    - ssh_setup
    # separate by host
    - role: yay
      tags: update
      vars:
        yay_packages:
          - downgrade
        yay_state: present
    - user
    - system
    - role: upgrade
      tags: update
    - role: syncthing
      when: syncthing_install
