---
- name: Sync dotfiles
  hosts: all
  pre_tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          # TODO: move package lists to separate file?
          - git
        state: present
      tags: update
  roles:
    - ssh_setup
    - role: yay
      tags: update
      vars:
        packages:
          - downgrade
        state: present
    - user
    - system
    - role: upgrade
      tags: update
