---
- name: Sync dotfiles
  hosts: all
  roles:
    - role: yay
      vars:
        packages:
          - downgrade
        state: present
    - user
    - system
    - role: upgrade
      vars:
        allow_reboot: false
  pre_tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          # TODO: move package lists to separate file?
          - git
        state: present
