---
- name: Sync dotfiles
  hosts: all
  pre_tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          # TODO: move package lists to separate file?
          - git
          - zsh
          - curl
        state: present
      tags: update
  roles:
    - ssh_setup
    # separate by host
    - role: yay
      vars:
        yay_packages:
          - downgrade
        yay_state: present
      tags: update
      when: ansible_facts['distribution'] | lower == 'archlinux'
    - user
    - system
    - role: upgrade
      tags: update
    # - role: syncthing
    #   when: syncthing_install
