---
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"

- name: Setup dotfiles
  ansible.builtin.shell:
    chdir: "{{ dotfiles_dir }}"
    cmd: "{{ dotfiles_install_cmd }}"
  register: dotbot_setup_result

- name: Debug dotfile setup log
  ansible.builtin.debug:
    var: dotbot_setup_result.stdout

- name: Debug dotfile setup errors
  ansible.builtin.debug:
    var: dotbot_setup_result.
  when: dotbot_setup_result.stderr != ""
