---
- name: Set git config options
  ansible.builtin.shell:
    cmd: |
      git config --global pull.rebase true
      git config --global user.name {{ ansible_user }}

- name: Set user dotfiles
  include_tasks: dotfiles.yml
  tags: dotfiles
  when: dotfiles_repo is defined

- name: Hush login
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.hushlogin"
    state: touch
  when: ansible_facts['distribution'] | lower == 'ubuntu'

- name: Clone wallpapers repo
  ansible.builtin.git:
    repo: "{{ wallpapers_repo }}"
    dest: "{{ wallpapers_dir }}"
    accept_hostkey: true
  when: wallpapers_repo is defined

# - name: Update vim-plug
#   ansible.builtin.shell: vim -c 'PlugUpgrade' -c 'PlugUpdate' -c 'qa!'

- name: "Change user shell to {{ shell }}"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "{{ shell }}"
  when: ansible_facts['user_shell'] != shell

# https://wiki.archlinux.org/index.php/Zsh#Persistent_rehash
- name: Rehash zsh $PATH
  ansible.builtin.shell: |
    if [[ "$SHELL" = *"zsh" ]]; then
      REHASH_FILE=$HOME/.cache/zsh/rehash
      mkdir -p "${REHASH_FILE%/*}"
      /usr/bin/touch -m "$REHASH_FILE"
    else
      echo "Skipping...current shell is $SHELL"
    fi
  when: ansible_facts['user_shell'] == '/usr/bin/zsh'

- name: Set user X11 settings
  include_tasks: x11_settings.yml
  when: x11_enabled
