---
# Docs: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: upgrade

- name: Update packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  tags: upgrade

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  tags: upgrade

- name: Upgrade the OS
  ansible.builtin.apt:
    upgrade: dist
  when: allow_dist_upgrade is true

- name: Evaluate reboot
  when: allow_reboot is true
  block:
    - name: Determine whether to restart
      ansible.builtin.stat:
        # https://wiki.ubuntu.com/UpdateNotifier
        path: /var/run/reboot-required
        get_attributes: false
        get_checksum: false
        get_mime: false
      register: upgrade__should_restart_stat

    - name: Print reboot status
      ansible.builtin.debug:
        msg: "Reboot {{ (upgrade__should_restart_stat.stat.exists is true) | ternary('is', 'is not') }} required to complete the upgrade"

    # See defaults: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html
    - name: Reboot
      ansible.builtin.reboot:
      when: upgrade__should_restart_stat.stat.exists is true and allow_reboot is true
