kind: Secret
ansible_user: ENC[AES256_GCM,data:O17bS70=,iv:AEXdFlpSxx35LswCx49htVrjSaGnAwHgYMWnoMuGbNM=,tag:3jE8cXoW5smkHxdr8n4SdA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6U9t9X97bPoJRALw,iv:VUdLqgWvGauO96TZTThtXagdzLniojsTPdEZAaSCXFM=,tag:TI+M/fAgpZ1SdGYNZUelOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOFZDYWpTNFZWTkN1dlVp
            MEJsdlhTN0FleXZxQnJDV2E5aC9kc0FTc1NNCk1IZ2R5TDJKNndHa1dBMGxRd1d6
            MTZsUlJzSDZqNm9SZUVoOXpjTDI5VWcKLS0tIHk5YSt3d0ExYmdkYTRqVGZLc3pH
            T1lKVUVLdVNhNW9Bdnl0akVnQnVTUFkK5f9DFn4RDff/P9oMDYc0KK9aKxM+uTxA
            30ZIIWS+sBxLd/wXxmkiRlG7Kk4xgNe24wwdIYRMOLM/YnMnCIrclQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-09T18:22:44Z"
    mac: ENC[AES256_GCM,data:pURjRIxDEljSzuwYDn2hk7RnNXPJl1uiBxx/OCSiefCETSBvDw+jzNjt4UCwaSnleXpBnOgnUwTK9dIix3DkkaKfFsY57y6D8uiHnxZSYVB0LoVWj582U5gTGe0N1MAQ9xIy2qXF5UBYZGZRfm6RDdthemu7ag32+2PYl2prg24=,iv:R4IVJRyySx0A8QNJv7E7gO8uiyBliglQFRlE2+2lymY=,tag:rJGtWSHpZpqnYjXg+ksMvg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
