kind: Secret
ansible_user: ENC[AES256_GCM,data:aV7VprM=,iv:yBUDC/Q+cUugEO3cZxsWRxirgq/v0YMv7ArESPgiGyU=,tag:HlFToE1Z27IZBndcDuGEBg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:g1bGYJPoLsNoq3hP,iv:d69UQoq24u6Km8FHEfTRSugHhvrrqmZkefOPSZA/BZs=,tag:yW5+vqI2k5zRVHTSwqBK9w==,type:str]
healthchecks__snapraid_runner_uuid: ENC[AES256_GCM,data:Cl9DFdMbA9LrmEuUO/1xxDSyaLLoqsdTZ6XB5Hiejdj2X4AQ,iv:9bhGEIprC9PxtIjjQsWgEw7dHRuNtDTBbXEpBxfNTl0=,tag:JqGCY43D9M0ce0gprSuHKw==,type:str]
healthchecks__ping_url: ENC[AES256_GCM,data:P9qTyKyKBb8x8t+75bSzmlbFNRaG5J0+lA==,iv:pivl92XFq8W7weM1webh39z237wYlfYC9jKw4TxQ2ZE=,tag:SXKiZJ6WgA70P09Obxy6qw==,type:str]
snapraid__daemon_net_allowed_origin: ENC[AES256_GCM,data:o7NUXSHndM2cJbZTmD0S2vlBWIJITv0Tryc=,iv:o0uAZTTCJPj++Vq4jtztv6SHQiYAF51bf5UU8HFyTp0=,tag:ixoBq/WGgG4IA/1Jo1Caew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmtWdk4vY0RuUjZOdzVW
            VVlNWkxnQS85KzJQdnZzZWJDN0E5YmV4VkZzCit0NmFQUWZXWEprN1c2Z1orVkdE
            THNaOGpTaHEvbHZxdi9Fb2RYM2M1SzgKLS0tIGdEZTRWQk84Yjh3WExzYjNUcGEr
            b3BIMlBDQ3FDSE50eFc5dzlOUW1USzQKRqbY6ymIODAy/CaMm8ayeXzMKYhrmDqi
            kSHLHH6w1kPLKNrjllSX3s3Lp6h4iypc0zOk0VP4DPRo4dc/2sAAGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
    lastmodified: "2026-06-15T05:42:22Z"
    mac: ENC[AES256_GCM,data:7KqOeMSXRRZIZwO0aGyqJgMg0alarfiztY7dEu4w5m0W64IAJ9aK65HW0Xp7qL5AMl+TohYscg9sGG0xBBgQDf8XHD8UoNvccaTxg5dWAf3HJTXJYq6uJTuamxi1I04Sici4TJnWCzvM0OZgkNyUCsAthRtmg1FRZkqVE8c64Ko=,iv:bXQ6DocvpZ7IdMivAcKG8ZmN0xaU+O3ZFT+VpjSRknI=,tag:LoL6eMRtMTGPj4BXbf7uSQ==,type:str]
    unencrypted_regex: ^(kind)$
    version: 3.13.1
