kind: Secret
ansible_user: ENC[AES256_GCM,data:1jR6qWg=,iv:RszXjomvjx/7WStQ3cl6JDVkgs6bYzZGGOUHm1+d1Lk=,tag:17koOxxTGLdUcAK8UYukmw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:dpbX5BmnrbZgCmJ6,iv:lnmt0nvnWV5q6OT3g9xGdEWih24bhw+gTWUm9VjPxps=,tag:s+HuQGlU2JNvwjWBbONLnA==,type:str]
proxmox__api_user: ENC[AES256_GCM,data:F51CA2lEKnQ=,iv:LlItd8SpBTWSq/d8g7AIPy5kEgAerhwvcWOwajEyjpI=,tag:ZcN4VF6t0yLwiLOoKMyTWg==,type:str]
proxmox__api_password: ENC[AES256_GCM,data:nRnh89yPis8oIPoz/z+dXYmqmRbl5lmo,iv:PDaWURHNYrlSQMZW/yKjAtLtm5odn7fxZgg97xWKvQo=,tag:DBoNwQ0nHWu6WgAGxozJ/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYjVTcTcrQ0ZFQVExN2FE
            ZE1aQ2U0RGFEWExtTlJ0WHhYT1hyWWFXZHhBCmFjbXN6SCthNEFEQlQxSFhHTnBS
            cGpDclM3aVZZdE44S05HUXhGdUw1elkKLS0tIGNXd1VTUEpiODRROUFzQ2duZ3Fy
            RUdFclVZUTJaWXFHQ3llK1hnUTl2R2cKm2nk9aZSGzjcC9dPQoqyv/5z7aGX24PR
            Yg0qFDtbXFX3IvT1OrY7pwAanw1mWBFlyNfIkdLZnnjF1moGm4LEog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T20:29:00Z"
    mac: ENC[AES256_GCM,data:bsnnylIt/sGOBIi9cPCrchX72CfFFS9r0Ck7MjbbVfheMr8fi4dgsJ9KW3aRsVgvkiYz/5SjgJYt+ouAcbI/wSRLNox1seK/y4lBA9YtfwFVboaXUY5Ge7bwryC3n999pvCyiYE6T65/QdYeM1WSKDFgKFne4dvH2MKYjHrazX4=,iv:rcQBwd6bJkqSUB12jA9q8CwR3e1GGR74U4fgK5F5TNY=,tag:K8llaNYWb76NLxR2CGL7bQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.8.1
