---
- name: Install dependencies
  ansible.builtin.package:
    state: present
    name:
      - nfs-common
      - nfs-kernel-server

- name: Set NFS service
  ansible.builtin.set_fact:
    nfs__server_daemon: nfs-kernel-server.service
