# Security:
# - https://github.com/konstruktoid/ansible-role-hardening
# - https://github.com/dev-sec/ansible-collection-hardening
---
- name: Check supported distribution
  ansible.builtin.fail:
    msg:
      - "Unsupported distribution: {{ ansible_facts['distribution'] | lower }}"
      - "Supported role distributions are {{ os__supported_distributions }}"
  when: ansible_facts['distribution'] | lower not in os__supported_distributions

- name: "Set timezone {{ os__timezone }}"
  community.general.timezone:
    name: "{{ os__timezone }}"

- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Setup hosts
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] | lower }}.yaml"
