---
# https://wiki.archlinux.org/title/Intel_GVT-g
- name: Add kernel modules for Intel GVT
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - kvmgt

- name: Enable GVT
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!{{ item }}).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 {{ item }}"'
    backup: true
    backrefs: true
  notify: update grub
  loop:
    - i915.enable_gvt=1
    # - iommu=pt
    # - pcie_acs_override=downstream,multifunction
    # - vfio_iommu_type1.allow_unsafe_interrupts=1
    # - kvm.ignore_msrs=1
