# Example https://github.com/alacritty/alacritty/blob/master/alacritty.yml
window:
    padding:
        x: 40
        y: 40

font:
    normal:
        family: "Fira Code"
    bold:
        family: "Fira Code"
    italic:
        family: "Fira Code"
    size: 8.0

# https://github.com/alacritty/alacritty/wiki/Color-schemes
schemes:
    gruvbox_dark: &dark
        primary:
            background: "0x282828"
            foreground: "0xdfbf8e"
        normal:
            black: "0x665c54"
            red: "0xea6962"
            green: "0xa9b665"
            yellow: "0xe78a4e"
            blue: "0x7daea3"
            magenta: "0xd3869b"
            cyan: "0x89b482"
            white: "0xdfbf8e"
        bright:
            black: "0x928374"
            red: "0xea6962"
            green: "0xa9b665"
            yellow: "0xe3a84e"
            blue: "0x7daea3"
            magenta: "0xd3869b"
            cyan: "0x89b482"
            white: "0xdfbf8e"

    gruvbox_light: &light
        primary:
            background: "0xf9f5d7" # hard contrast
            # background: '0xfbf1c7' # medium contrast
            # background: '0xf2e5bc' # soft contrast
            foreground: "0x3c3836"
        normal:
            black: "0xfbf1c7"
            red: "0xcc241d"
            green: "0x98971a"
            yellow: "0xd79921"
            blue: "0x458588"
            magenta: "0xb16286"
            cyan: "0x689d6a"
            white: "0x7c6f64"
        bright:
            black: "0x928374"
            red: "0x9d0006"
            green: "0x79740e"
            yellow: "0xb57614"
            blue: "0x076678"
            magenta: "0x8f3f71"
            cyan: "0x427b58"
            white: "0x3c3836"

    # Gruvbox Material Dark
    gruvbox_material: &alt-dark
        primary:
            background: "0x1d2021" # hard
            #background: "0x282828" # medium
            foreground: "0xdfbf8e"

        normal:
            black: "0x665c54"
            red: "0xea6962"
            green: "0xa9b665"
            yellow: "0xe78a4e"
            blue: "0x7daea3"
            magenta: "0xd3869b"
            cyan: "0x89b482"
            white: "0xdfbf8e"

        bright:
            black: "0x928374"
            red: "0xea6962"
            green: "0xa9b665"
            yellow: "0xe3a84e"
            blue: "0x7daea3"
            magenta: "0xd3869b"
            cyan: "0x89b482"
            white: "0xdfbf8e"

#colors: *dark
colors: *alt-dark

draw_bold_text_with_bright_colors: false

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
bell:
    animation: EaseOutExpo
    color: "0x282828"
    duration: 0

# Background opacity
background_opacity: 1.0

# Mouse bindings
#
# Available fields:
# - mouse
# - action
# - mods (optional)
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# All available `mods` and `action` values are documented in the key binding
# section.
mouse_bindings:
    - { mouse: Middle, action: PasteSelection }

cursor:
    # Cursor style
    #
    # Values for 'style':
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    style: Block

    # If this is `true`, the cursor will be rendered as a hollow box when the
    # window is not focused.
    unfocused_hollow: true
