---
x-options: &options
  profiles: [utils]
  networks: [default]
  environment: &environment
    TZ: "${TIMEZONE}"
  deploy:
    restart_policy:
      condition: unless-stopped

x-media-volume:
  driver_opts: &media_driver_opts
    type: nfs
    o: addr=${MEDIA_IP},hard,timeo=600,retrans=3,proto=tcp,nfsvers=4.2,port=2049,rsize=4096,wsize=4096,noacl,nocto,noatime,nodiratime
    device: :/

x-media-volume-nocache:
  driver_opts: &media_driver_nocache_opts
    type: nfs
    o: addr=${MEDIA_IP},hard,timeo=600,retrans=3,proto=tcp,nfsvers=4.2,port=2049,rsize=4096,wsize=4096,noacl,nocto,noatime,nodiratime,fg,noac,lookupcache=none
    device: :/

# TODO: use new volume subpaths feature: https://docs.docker.com/compose/compose-file/05-services/#volumes
volumes:
  media:
    name: media
    driver_opts:
      <<: *media_driver_opts
      device: :/media
  media_library:
    name: media_library
    driver_opts:
      <<: *media_driver_opts
      device: :/media/library
  books:
    name: books
    driver_opts:
      <<: *media_driver_opts
      device: :/media/library/books
  usenet:
    name: usenet
    driver_opts:
      <<: *media_driver_nocache_opts
      device: :/media/usenet
  cameras:
    name: cameras
    driver_opts:
      <<: *media_driver_opts
      device: :/media/cameras

services:
  cloudflare-ddns:
    <<: *options
    image: ghcr.io/brettinternet/cloudflare-ddns:latest
    container_name: ddns
    environment:
      <<: *environment
      CRON: "*/10 * * * *"
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
      CLOUDFLARE_RECORD_NAME: "local.${PRIVATE_DOMAIN}"
      CLOUDFLARE_RECORD_PROXIED: "false"
      CLOUDFLARE_RECORD_TYPE: A

  mealie:
    <<: *options
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1
    container_name: mealie
    environment:
      <<: *environment
      WEB_CONCURRENCY: 1
      MAX_WORKERS: 1
      PUID: "${PUID}"
      PGID: "${PGID}"
      TOKEN_TIME: 720 # 24 hours * 30 days
      BASE_URL: "https://recipes.${PUBLIC_DOMAIN}"
      AUTO_BACKUP_ENABLED: "true"
      ALLOW_SIGNUP: "false"
    volumes:
      - "${CONFIG_DIR}/mealie:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.mealie.rule: Host(`recipes.${PUBLIC_DOMAIN}`)
      traefik.http.routers.mealie.entrypoints: websecure
      traefik.http.services.mealie.loadbalancer.server.port: 9000

  ilo-fans-controller:
    <<: *options
    image: ghcr.io/alex3025/ilo-fans-controller
    container_name: ilofans
    environment:
      <<: *environment
      ILO_HOST: "10.1.2.7"
      ILO_USERNAME: "${ILO_USERNAME}"
      ILO_PASSWORD: "${ILO_PASSWORD}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.ilofan.rule: Host(`ilofans.${PRIVATE_DOMAIN}`)
      traefik.http.routers.ilofan.entrypoints: websecure
      traefik.http.services.ilofan.loadbalancer.server.port: 80
