# Security:
# - https://github.com/konstruktoid/ansible-role-hardening
# - https://github.com/dev-sec/ansible-collection-hardening
---
- name: Check supported distribution
  fail:
    msg:
      - "Unsupported distribution: {{ ansible_facts['distribution'] | lower }}"
      - "Supported role distributions are {{ supported_distributions }}"
  when: ansible_facts['distribution'] | lower not in supported_distributions

- name: Setup hosts
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] | lower }}.yaml"
