---
- name: Log host vars
  hosts:
    - all
  become: true
  pre_tasks:
    - name: Install AUR dependencies
      ansible.builtin.include_role:
        name: aur
      vars:
        state: latest
        packages: needrestart

  tasks:
    - name: Find reboot-required file
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: debian_reboot_required_result
      when: ansible_facts['distribution'] | lower == 'debian'

    - name: Find reboot-required file
      ansible.builtin.command: needrestart -q
      register: archlinux_reboot_required_result
      when: ansible_facts['distribution'] | lower == 'archlinux'

    - name: Set reboot requirement fact
      ansible.builtin.set_fact:
        reboot_required: >-
          {{ archlinux_reboot_required_result.rc != 0
          if ansible_facts['distribution'] | lower == 'archlinux'
          else debian_reboot_required_result.stat.exists }}

    - name: Host vars
      ansible.builtin.debug:
        msg:
          - "Distribution: {{ ansible_facts['distribution'] }}, version: {{ ansible_distribution_version }}"
          - "Processor: {{ ansible_processor | select('match', '.*CPU.*') | list | unique | first }}"
          - "Reboot required: {{ reboot_required }}"

    - name: Local vars
      ansible.builtin.debug:
        msg:
          - "Project root directory: {{ lookup('ansible.builtin.env', 'ROOT_DIR') }}"
      when: inventory_hostname == ansible_play_hosts_all[0] # preferred over run_once?
