---
- name: Check supported distribution
  ansible.builtin.fail:
    msg:
      - "Unsupported distribution: {{ ansible_facts['distribution'] | lower }}."
      - This role only supports Arch Linux.
  when:
    - ansible_facts['distribution'] | lower != 'archlinux'

- name: Set user X11 settings
  ansible.builtin.include_tasks: x11_settings.yaml
