---
# Docs: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

- name: Update package cache (apt)
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update packages (apt)
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Remove dependencies that are no longer required (apt)
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Upgrade the OS (apt)
  ansible.builtin.apt:
    upgrade: dist
  when: allow_dist_upgrade is true

- name: Determine whether to restart (Ubuntu)
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: upgrade__should_restart_stat

- name: Print reboot status
  ansible.builtin.debug:
    msg: "Reboot {{ (upgrade__should_restart_stat.stat.exists is true) | ternary('is', 'is not') }} required to complete the upgrade"

# See defaults: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html
- name: Reboot
  become: true
  ansible.builtin.reboot:
  when: upgrade__should_restart_stat.stat.exists is true and allow_reboot is true
