---
- name: Setup NFS server
  hosts: bogota
  become: true
  roles:
    - role: snapraid
      when: snapraid is true
    - role: mergerfs
      when: mergerfs__mounts is defined
    - role: nfs
      when: nfs__exports is defined
