---
- block:
    - name: Get keys from URL
      ansible.builtin.uri:
        url: "{{ ssh_keys_url }}"
        method: GET
        return_content: true
      register: keys_result
      failed_when:
        - keys_result['content'] == ""
        - "'ssh-rsa' not in keys_result['content']"

    - name: Filter key
      ansible.builtin.shell: "echo '{{ keys_result['content'] }}' | sed '{{ ssh_keys_line_number }}!d'"
      register: keys_sed_result
      when: ssh_keys_line_number is defined and ssh_keys_line_number | int > 0
      changed_when: false

    # - name: Set keys fact
    #   ansible.builtin.set_fact:
    #     ssh_keys: "{{ if (keys_sed_result is defined and keys_sed_result['stdout']) else keys_result['content'] }}"

    - name: Set filtered key fact
      ansible.builtin.set_fact:
        ssh_keys: "{{ keys_sed_result['stdout'] }}"
      when: keys_sed_result.stdout is defined

    - name: Set keys fact
      ansible.builtin.set_fact:
        ssh_keys: "{{ keys_result['content'] }}"
      when: keys_sed_result.stdout is not defined

    - name: Add key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_keys }}"
  when: ssh_keys_url is defined
