# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-bind
    namespace: networking
stringData:
    RNDC_ALGORITHM: ENC[AES256_GCM,data:z0M1v3e6Ppt2sgY=,iv:/9zvtrXwBwJC7zrLwgH6m9cWWiW0ZGhxRVNDzrFMCDY=,tag:BM4DNtYoypbjjKwJmvyElQ==,type:str]
    RNDC_SECRET: ENC[AES256_GCM,data:JUkwoBPehVQ9UaDWLwFBIf/B7dc1QbOdj/l+wWtb/onn/svi2uGzEmnf6Cw=,iv:nJV7l5F7hb4BLOFlGnKTse08RxGlP/tH19CUnGsTJ04=,tag:RRI53Hkk8S920jr4GGnK3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaVNsK0tnSkVTMWJuMGor
            N3RlTmFSbmlMeFBMazJCaFlRdjJ1VSthVkZNCmlqRXM2cEVIdThFRDJwVDZocytJ
            QjVNdkZVNGlHQ1o3bjZZdUMzVU9taUkKLS0tIDJXYjdBemlRUkY0VkdsSWtsTWJC
            NmlTcGlKa3FmVVpLd09qYWVSWTkyR3cK18yCPHqKmNsrwFSC+j0oKXI6ucUSgtAA
            FCOYIJOiWHd/EtEruegFrbj5vK3m7oCXKZ9zhVOYLbJ6xrVShDDl5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T03:24:04Z"
    mac: ENC[AES256_GCM,data:cB2xTGGu1nhY7BstL8zxuptx96nne5EhegLDmx7pPEMXY3u7QVsVP/EZUjOeyV7g1HxK02Ls6p1ETVsc0Dl04ynLQwAizeNPP367rBWxaVPUq29IJCz67n10GRlKmNarB9fF7qzUOQyC+E0A11aZDpL13kkPO6K0P1UbD1NBwFk=,iv:0ikOmnm69u9pwrwFQPXQC6zPHP7Sr26on6/Cthe1Bhk=,tag:XPJAOFFV/qaEffazFsDGlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
