---
# TODO: does this work?
- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
#
# - name: "Check for existing chocolatey install"
#   ansible.windows.win_stat:
#     path: "{{ chocolatey_path }}/choco.exe"
#   register: chocolatey_exe

# - name: "Install latest chocolatey"
#   ansible.builtin.raw:
#     "$env:chocolateyUseWindowsCompression='{{ chocolatey_windows_compression }}'; \
#     [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
#     iex ((New-Object System.Net.WebClient).DownloadString('{{ chocolatey_installer }}'))"
#   register: chocolatey_install_result
#   when:
#     - chocolatey_exe.stat.exists is defined
#     - not chocolatey_exe.stat.exists

# - name: "Add chocolatey to PATH"
#   ansible.windows.win_path:
#     name: PATH
#     elements: '%ALLUSERSPROFILE%\chocolatey\bin'
#     scope: machine
#     state: present
