---
all:
  children:
    home:
      children:
        linux:
          hosts:
            case:
              ansible_host: 10.1.1.14
              packages: >-
                {{
                  pkgs.base +
                  pkgs.i3 +
                  pkgs.laptop +
                  pkgs.i3_laptop +
                  pkgs.dev +
                  pkgs.x11
                }}
              aur_packages: >-
                {{
                  pkgs.base_aur +
                  pkgs.laptop_aur +
                  pkgs.i3_aur +
                  pkgs.i3_laptop_aur +
                  pkgs.dev_aur +
                  pkgs.x11_aur
                }}"

        windows:
          hosts:
            # https://docs.ansible.com/ansible/latest/os_guide/windows_setup.html
            # gameboy:
            #   ansible_host: 10.1.1.12
            #   packages:
            #     # base
            #     - name: git
            #       params: /NoGuiHereIntegration /NoShellIntegration /NoShellHereIntegration /WindowsTerminal /Editor:VisualStudioCode /NoAutoCrlf
            #     - name: spotify
            #     - name: discord
            #     - name: firefox
            #       params: /NoTaskbarShortcut /NoDesktopShortcut
            #     - name: chromium
            #     - name: 7zip
            #     - name: plexmediaplayer
            #     - name: coretemp
            #     - name: cpu-z
            #     - name: spacesniffer
            #     - name: lightshot
            #     - name: powertoys
            #     - name: vscode
            #       params: /NoDesktopIcon /NoQuicklaunchIcon
            #     - name: powershell-core
            #     - name: microsoft-windows-terminal
            #     - name: autohotkey
            #     - name: procmon
            #     - name: rufus
            #     - name: authy-desktop
            #     - name: voicemeeter-banana
            #     # Gaming
            #     - name: nvidia-display-driver
            #     - name: steam
            #     - name: epicgameslauncher
            #     - name: origin
            #     - name: goggalaxy
            #     - name: nvidia-geforce-now
            #     - name: uplay
            #     - name: vortex
            #     - name: logitech-options
