# when NAS is down
---
x-options: &options
  profiles: [media-lite]
  networks: [default]
  environment: &environment
    TZ: "${TIMEZONE}"
  deploy:
    restart_policy:
      condition: unless-stopped

services:
  frigate-lite:
    <<: *options
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    networks: [default]
    privileged: true
    environment:
      <<: *environment
      FRIGATE_RTSP_PASSWORD: "${FRIGATE_RTSP_PASSWORD}"
      FRIGATE_MQTT_PASSWORD: "${FRIGATE_MQTT_PASSWORD}"
    volumes:
      - "${CONFIG_DIR}/frigate-lite/config.yml:/config/config.yml"
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 8g
    shm_size: 8gb
    devices:
      - /dev/dri
      - /dev/bus/usb
    ports:
      - 127.0.0.1:5000:5000
      - 127.0.0.1:1984:1984 # go2rtc
      - 9554:8554 # RTSP
      - 8555:8555/tcp # WebRTC
      - 8555:8555/udp # WebRTC
    labels:
      traefik.enable: "true"
      traefik.http.routers.frigate.rule: Host(`video.${PRIVATE_DOMAIN}`)
      traefik.http.services.frigate.loadbalancer.server.port: 5000
      traefik.http.routers.frigate.entrypoints: websecure
      traefik.http.routers.frigate.service: frigate
      traefik.http.routers.go2rtc.rule: Host(`rtc.${PRIVATE_DOMAIN}`)
      traefik.http.services.go2rtc.loadbalancer.server.port: 1984
      traefik.http.routers.go2rtc.entrypoints: websecure
      traefik.http.routers.go2rtc.service: go2rtc
