---
x-options: &options
  profiles: [utils]
  networks: [default]
  environment: &environment
    TZ: "${TIMEZONE}"
  deploy:
    restart_policy:
      condition: unless-stopped

services:
  mealie:
    <<: *options
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1
    container_name: mealie
    environment:
      <<: *environment
      WEB_CONCURRENCY: 1
      MAX_WORKERS: 1
      PUID: "${PUID}"
      PGID: "${PGID}"
      TOKEN_TIME: 720 # 24 hours * 30 days
      BASE_URL: "https://recipes.${PUBLIC_DOMAIN}"
      AUTO_BACKUP_ENABLED: "true"
      ALLOW_SIGNUP: "false"
    volumes:
      - "${CONFIG_DIR}/mealie:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.mealie.rule: Host(`recipes.${PUBLIC_DOMAIN}`)
      traefik.http.routers.mealie.entrypoints: websecure
      traefik.http.services.mealie.loadbalancer.server.port: 9000

  slackbot:
    <<: *options
    image: ghcr.io/brettinternet/slackbot:main
    container_name: slackbot
    environment:
      <<: *environment
      LOG_LEVEL: debug
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 4200
      FEATURES: obituary,chat,vibecheck,aichat
      DATA_DIR: /app/data
      CONFIG_FILE: /app/data/config.yaml
      SLACK_TOKEN: "${SLACKBOT_SLACK_TOKEN}"
      SLACK_OBITUARY_NOTIFY_CHANNEL: "${SLACKBOT_SLACK_OBITUARY_NOTIFY_CHANNEL}"
      SLACK_SIGNING_SECRET: "${SLACKBOT_SLACK_SIGNING_SECRET}"
      SLACK_PREFERRED_USERS: "${SLACKBOT_SLACK_PREFERRED_USERS}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - "${CONFIG_DIR}/slackbot:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.slackbot.rule: Host(`bot.${PUBLIC_DOMAIN}`)
      traefik.http.routers.slackbot.entrypoints: websecure
      traefik.http.services.slackbot.loadbalancer.server.port: 4200
