---
x-options: &options
  profiles: [projects]
  networks: [default]
  environment: &environment
    TZ: "${TIMEZONE}"
  deploy:
    restart_policy:
      condition: unless-stopped

services:
  slackbot:
    <<: *options
    image: ghcr.io/brettinternet/slackbot:latest
    container_name: slackbot
    environment:
      <<: *environment
      LOG_LEVEL: debug
      SERVER_PORT: 4200
      DATA_DIR: /app/data
      CONFIG_FILE: /app/data/config.yaml
      SLACK_TOKEN: "${SLACKBOT_SLACK_TOKEN}"
      SLACK_USER_NOTIFY_CHANNEL: "${SLACKBOT_SLACK_OBITUARY_NOTIFY_CHANNEL}"
      SLACK_SIGNING_SECRET: "${SLACKBOT_SLACK_SIGNING_SECRET}"
      SLACK_PREFERRED_USERS: "${SLACKBOT_SLACK_PREFERRED_USERS}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - "${CONFIG_DIR}/slackbot:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.slackbot.rule: Host(`bot.${PUBLIC_DOMAIN}`)
      traefik.http.routers.slackbot.entrypoints: websecure
      traefik.http.services.slackbot.loadbalancer.server.port: 4200

  # multiplayer:
  #   <<: *options
  #   profiles: [server]
  #   image: ghcr.io/brettinternet/multiplayer:latest
  #   deploy:
  #     <<: *deploy
  #     replicas: 2
  #   environment:
  #     <<: *environment
  #     LOG_LEVEL: ${LOG_LEVEL:-info}
  #     POSTGRES_HOST: multiplayer-postgres
  #     POSTGRES_USER: ${MULTIPLAYER_DB_USERNAME}
  #     POSTGRES_PASSWORD: ${MULTIPLAYER_DB_PASSWORD}
  #     CLUSTER_MODE: "true"
  #     CORS_ALLOWED_ORIGINS: https://brett.cloud
  #     RATE_LIMIT_CONNECTION_TOKENS: 6
  #     RATE_LIMIT_CONNECTION_INTERVAL_SECONDS:  120
  #     RATE_LIMIT_MESSAGE_TOKENS: 10000
  #     RATE_LIMIT_MESSAGE_INTERVAL_SECONDS: 120
  #   labels:
  #     traefik.enable: "true"
  #     traefik.http.routers.multiplayer.rule: Host(`multiplayer.${PUBLIC_DOMAIN}`)
  #     traefik.http.routers.multiplayer.entrypoints: web
  #     traefik.http.services.multiplayer.loadbalancer.server.port: 3085

  # multiplayer-postgres:
  #   <<: *options
  #   image: postgres:17
  #   container_name: multiplayer-postgres
  #   environment:
  #     <<: *environment
  #     POSTGRES_USER: ${MULTIPLAYER_DB_USERNAME}
  #     POSTGRES_PASSWORD: ${MULTIPLAYER_DB_PASSWORD}
  #     POSTGRES_DB: multiplayer
  #   volumes:
  #     - "${CONFIG_DIR}/multiplayer-postgres:/var/lib/postgresql/data/"
