---
x-options: &options
  profiles: [projects]
  networks: [default]
  environment: &environment
    TZ: "${TIMEZONE}"
  restart: unless-stopped

services:
  slackbot:
    <<: *options
    image: ghcr.io/brettinternet/slackbot:latest
    container_name: slackbot
    environment:
      <<: *environment
      LOG_LEVEL: debug
      SERVER_PORT: 4200
      DATA_DIR: /app/data
      CONFIG_FILE: /app/data/config.yaml
      SLACK_TOKEN: "${SLACKBOT_SLACK_TOKEN}"
      SLACK_USER_NOTIFY_CHANNEL: "${SLACKBOT_SLACK_OBITUARY_NOTIFY_CHANNEL}"
      SLACK_SIGNING_SECRET: "${SLACKBOT_SLACK_SIGNING_SECRET}"
      SLACK_PREFERRED_USERS: "${SLACKBOT_SLACK_PREFERRED_USERS}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - "${CONFIG_DIR}/slackbot:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.slackbot.rule: Host(`bot.${PUBLIC_DOMAIN}`)
      traefik.http.routers.slackbot.entrypoints: websecure
      traefik.http.services.slackbot.loadbalancer.server.port: 4200
