---
x-options: &options
  profiles: [utils]
  networks: [default]
  environment: &environment
    TZ: "${TIMEZONE}"
  deploy:
    restart_policy:
      condition: unless-stopped

services:
  mealie:
    <<: *options
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1
    container_name: mealie
    environment:
      <<: *environment
      WEB_CONCURRENCY: 1
      MAX_WORKERS: 1
      PUID: "${PUID}"
      PGID: "${PGID}"
      TOKEN_TIME: 720 # 24 hours * 30 days
      BASE_URL: "https://recipes.${PUBLIC_DOMAIN}"
      AUTO_BACKUP_ENABLED: "true"
      ALLOW_SIGNUP: "false"
    volumes:
      - "${CONFIG_DIR}/mealie:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.mealie.rule: Host(`recipes.${PUBLIC_DOMAIN}`)
      traefik.http.routers.mealie.entrypoints: websecure
      traefik.http.services.mealie.loadbalancer.server.port: 9000

  slackbot:
    <<: *options
    image: ghcr.io/brettinternet/slackbot:main
    container_name: slackbot
    environment:
      <<: *environment
      LOG_LEVEL: debug
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 4200
      FEATURES: obituary,chat,vibecheck,aichat
      DATA_DIR: /app/data
      CONFIG_FILE: /app/data/config.yaml
      SLACK_TOKEN: "${SLACKBOT_SLACK_TOKEN}"
      SLACK_OBITUARY_NOTIFY_CHANNEL: "${SLACKBOT_SLACK_OBITUARY_NOTIFY_CHANNEL}"
      SLACK_SIGNING_SECRET: "${SLACKBOT_SLACK_SIGNING_SECRET}"
      SLACK_PREFERRED_USERS: "${SLACKBOT_SLACK_PREFERRED_USERS}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - "${CONFIG_DIR}/slackbot:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.slackbot.rule: Host(`bot.${PUBLIC_DOMAIN}`)
      traefik.http.routers.slackbot.entrypoints: websecure
      traefik.http.services.slackbot.loadbalancer.server.port: 4200

  atuin:
    <<: *options
    image: ghcr.io/atuinsh/atuin:latest
    container_name: atuin
    command: server start
    user: "${PUID}:${PGID}"
    links:
      - atuin-postgres:db
    environment:
      <<: *environment
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@db/atuin
      RUST_LOG: info,atuin_server=info
    volumes:
      - "${CONFIG_DIR}/atuin:/config"
    labels:
      traefik.enable: "true"
      traefik.http.routers.atuin.rule: Host(`sh.${PRIVATE_DOMAIN}`)
      traefik.http.routers.atuin.entrypoints: websecure
      traefik.http.services.atuin.loadbalancer.server.port: 8888

  atuin-postgres:
    <<: *options
    image: postgres:17
    container_name: atuin-postgres
    environment:
      <<: *environment
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: atuin
    volumes:
      - "${CONFIG_DIR}/atuin-postgres:/var/lib/postgresql/data/"

  linkding:
    <<: *options
    container_name: linkding
    image: sissbruecker/linkding:latest
    volumes:
      - "${CONFIG_DIR}/linkding:/etc/linkding/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.linkding.rule: Host(`bookmarks.${PUBLIC_DOMAIN}`)
      traefik.http.routers.linkding.entrypoints: websecure
      traefik.http.services.linkding.loadbalancer.server.port: 9090

  streetmerchant:
    <<: *options
    container_name: streetmerchant
    image: ghcr.io/jef/streetmerchant:latest
    environment:
      <<: *environment
      MAX_PRICE_SERIES_5070TI: 800
      SHOW_ONLY_SERIES: 5070ti
      SHOW_ONLY_COUNTRY: US
      STORES: amazon,newegg,bestbuy,pny
      PUSHOVER_USER: "${PUSHOVER_USER_KEY}"
      PUSHOVER_TOKEN: "${PUSHOVER_STREETMERCHANT_TOKEN}"
      PAGE_SLEEP_MIN: 60000

  n8n:
    <<: *options
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    links: [n8n-postgres]
    depends_on: [n8n-postgres]
    environment:
      <<: *environment
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n-postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: ${N8N_DB_USERNAME}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
    volumes:
      - "${CONFIG_DIR}/n8n:/home/node/.n8n"
    labels:
      traefik.enable: "true"
      traefik.http.routers.n8n.rule: Host(`n8n.${PRIVATE_DOMAIN}`)
      traefik.http.routers.n8n.entrypoints: websecure
      traefik.http.services.n8n.loadbalancer.server.port: 5678

  n8n-postgres:
    <<: *options
    image: postgres:17
    container_name: n8n-postgres
    environment:
      <<: *environment
      POSTGRES_USER: ${N8N_DB_USERNAME}
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD}
      POSTGRES_DB: n8n
    volumes:
      - "${CONFIG_DIR}/n8n-postgres:/var/lib/postgresql/data/"
