---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skipci')"
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: uv
      - run: uvx yamllint .

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skipci')"
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: shellcheck
      - run: >-
          find . -type f
          \( -name '*.sh' -o -name '*.bash' -o -name '*.ksh' -o -name '*.bashrc'
          -o -name '*.bash_profile' -o -name '*.bash_login' -o -name '*.bash_logout' \)
          -not -path "./dotbot/*"
          | xargs shellcheck

  dprint:
    name: dprint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skipci')"
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: dprint
      - run: dprint check

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skipci')"
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: bun prettier
      - run: prettier --check "**/*.{yaml,yml}"
